export type UniverseCharacter = {
  id: string;
  chamber: string;
  glyph: string;
  apparentAge: number | null;
  portrait?: string;
  nameZh: string; nameEn: string;
  roleZh: string; roleEn: string;
  bioZh: string; bioEn: string;
  appearanceZh: string; appearanceEn: string;
  motivationZh: string; motivationEn: string;
  continuityZh: string; continuityEn: string;
  storySlugs: string[];
};

export const universeCharacters: UniverseCharacter[] = [
  { id:'mira', chamber:'obsidian-court', glyph:'钟', apparentAge:22, portrait:'/images/characters/mira.webp', nameZh:'弥拉', nameEn:'Mira', roleZh:'无龄见习守钟人', roleEn:'Ageless bell apprentice', bioZh:'她的年龄在最后一次日出时停止。如今，她掌握着让时间重新前进的第十三声。', bioEn:'Her age stopped at the final sunrise. Now she holds the thirteenth chime that may restart time.', appearanceZh:'橄榄色苍白皮肤，灰眼，齐颌黑发；右鬓有一缕银发。常穿灰蓝旧斗篷，颈前系青铜调音钥匙。', appearanceEn:'Olive-pale skin, grey eyes, jaw-length black hair with a silver streak at the right temple; worn ash-blue cloak and bronze tuning key.', motivationZh:'让时间重新流动，同时拒绝把任何人的牺牲当作理所当然。', motivationEn:'Restart time without accepting any sacrifice as inevitable.', continuityZh:'外表恒定为二十二岁；右鬓银发、调音钥匙和指尖煤灰不可缺失。她不知道奥德林已进入钟体，直到第三幕才确认。', continuityEn:'Appears twenty-two; silver streak, tuning key, and soot-stained fingertips are invariant. She does not confirm Odren entered the bell until act three.', storySlugs:['the-bell-that-never-saw-dawn'] },
  { id:'odren', chamber:'obsidian-court', glyph:'羽', apparentAge:58, nameZh:'奥德林', nameEn:'Odren', roleZh:'失踪的第十三守钟人', roleEn:'Missing thirteenth keeper', bioZh:'他把自己铸进钟里，只为给黎明留下最后一种可能。', bioEn:'He cast himself into the bell to preserve one final possibility of dawn.', appearanceZh:'褐色皮肤，琥珀眼，短灰黑发与方形短须；双手留有钟铸伤痕，穿黑色厚呢守钟人长衣。', appearanceEn:'Brown skin, amber eyes, close-cropped salt-and-pepper hair and square beard; scarred bell-founder hands and heavy black keeper coat.', motivationZh:'为黎明保留最后一种可能，同时让弥拉拥有真正选择而非服从命令。', motivationEn:'Preserve one final possibility of dawn and leave Mira a genuine choice rather than an order.', continuityZh:'暮辉纪427年时五十八岁；失踪后只能通过刻痕、回声、旧物和钟内意识出现，不能以完整肉身返回。', continuityEn:'Fifty-eight in Gloaming 427; after vanishing he appears only through carvings, echoes, objects, and consciousness within the bell—never restored bodily.', storySlugs:['the-bell-that-never-saw-dawn'] },
  { id:'old-king', chamber:'obsidian-court', glyph:'王', apparentAge:null, nameZh:'旧王', nameEn:'The Old King', roleZh:'沉睡在城下的无名君主', roleEn:'Nameless monarch beneath the city', bioZh:'他以自己的名字为代价封存黎明，让王庭活在不会结束的一天。', bioEn:'He traded his name to seal away dawn and leave the Court inside an unending day.', appearanceZh:'只以梦中剪影和壁画残片出现：高大衰老的人形，戴十二层薄黑金属冠，面部是被刮除的空白。', appearanceEn:'Seen only in dreams and ruined murals: a tall aged silhouette, twelve-layer black-metal crown, face scraped into blankness.', motivationZh:'让王庭免于一次被预言的日出灾难，即使代价是所有未来。', motivationEn:'Spare the Court from a prophesied sunrise catastrophe, even at the cost of every future.', continuityZh:'绝不展示清晰面孔或真名；只能通过十二层王冠、无脸壁画和地下梦声辨认。是否真为暴君保持开放。', continuityEn:'Never show a clear face or true name; identified only by the twelve-layer crown, faceless murals, and dreams below. Whether he was truly a tyrant remains unresolved.', storySlugs:['the-bell-that-never-saw-dawn'] },
  { id:'blackwing-chief', chamber:'obsidian-court', glyph:'判', apparentAge:52, nameZh:'黑羽首席', nameEn:'First Blackwing', roleZh:'黑羽审判庭首席', roleEn:'Chief of the Blackwing Tribunal', bioZh:'他用秩序保护王庭，也在第十三声前第一次承认，手续完整不等于选择真实。', bioEn:'He protects the Court through order and, before the thirteenth chime, admits that complete procedure is not the same as genuine choice.', appearanceZh:'五十二岁，冷白肤色，深灰眼，黑发夹银并向后梳；左耳前有旧烧痕，穿无装饰黑呢法衣，领口别一枚磨损黑羽。', appearanceEn:'Fifty-two, cool pale skin, dark-grey eyes, black hair streaked with silver and brushed back; an old burn before the left ear, plain black wool judicial coat, and a worn black feather at the collar.', motivationZh:'避免王庭因突然恢复全部可能而崩溃，同时逐步承认秩序不能替人选择。', motivationEn:'Prevent the Court collapsing under restored possibilities while learning that order cannot choose for others.', continuityZh:'五十二岁；左耳前烧痕、磨损黑羽与无装饰黑法衣固定。第十三声前不主动协助弥拉，直到桥面将断才用佩剑撑住齿轮。', continuityEn:'Fifty-two; burn before the left ear, worn feather, and plain black coat are invariant. He does not actively aid Mira before the chime, bracing the failing gear with his sword only at the final moment.', storySlugs:['the-bell-that-never-saw-dawn'] },
  { id:'caelis', chamber:'obsidian-court', glyph:'翼', apparentAge:41, nameZh:'赛勒斯', nameEn:'Caelis', roleZh:'长翼审判官', roleEn:'The Winged Judge', bioZh:'被王庭写成圣人的囚犯，醒来后决定审判制造圣像的世界。', bioEn:'A prisoner rewritten as a saint who wakes to judge the world that made his image.', appearanceZh:'高瘦，浅棕肤色，剃短黑发，左眉一道竖疤；黑铜审判甲外覆折翼状灰石披肩。', appearanceEn:'Tall and angular, pale umber skin, shaved black hair, vertical scar through the left brow; blackened-bronze judicial armour and folded stone-grey mantle.', motivationZh:'夺回被圣像和官方判词篡改的自我，并让被删去的证词重新进入公共记忆。', motivationEn:'Recover the self rewritten by sainthood and return erased testimony to public memory.', continuityZh:'肉身四十一岁，石化历时三百一十四年；石翼不能飞，只能遮挡、承重和留下石屑。', continuityEn:'Body aged forty-one after 314 years in stone; stone wings cannot fly, only shelter, bear weight, and shed grit.', storySlugs:['the-thirteenth-trial-of-the-winged-judge'] },
  { id:'veyra', chamber:'obsidian-court', glyph:'凿', apparentAge:34, nameZh:'薇尔', nameEn:'Veyra', roleZh:'圣像修复师', roleEn:'Conservator of statues', bioZh:'她在修复圣像时唤醒赛勒斯，也在空白判词上看见了自己的名字。', bioEn:'She wakes Caelis while restoring his statue and finds her own name on the blank verdict.', appearanceZh:'三十四岁，暖白肤色，短栗发，榛色眼；左手戴三指皮手套，深红工作围裙上沾有白色石粉。', appearanceEn:'Thirty-four, warm pale skin, short chestnut hair, hazel eyes, three-finger leather glove on the left hand and a dark-red apron dusted white.', motivationZh:'保存被官方修复工程抹除的真实裂缝与证据。', motivationEn:'Preserve the true fractures and evidence erased by official restoration.', continuityZh:'三十四岁；左手缺小指与无名指末节，以三指手套遮护。她从不称赛勒斯为圣人。', continuityEn:'Thirty-four; missing the left little finger and tip of the ring finger, protected by a three-finger glove. She never calls Caelis a saint.', storySlugs:['the-thirteenth-trial-of-the-winged-judge'] },
  { id:'evren', chamber:'stagcrown-wilds', glyph:'鹿', apparentAge:29, nameZh:'伊芙兰', nameEn:'Evren', roleZh:'无名猎人', roleEn:'The Nameless Hunter', bioZh:'她折断王冠，拒绝让任何人替森林承担遗忘。', bioEn:'She broke the crown and refused to let any one life carry the forest’s forgetting.', appearanceZh:'日晒雀斑皮肤，绿褐眼，深赤褐长发编成不整齐的实用辫；鼻梁有旧伤，穿苔绿猎装。', appearanceEn:'Sun-browned freckled skin, green-brown eyes, dark auburn practical braid, healed cut across the nose, moss-green hunting clothes.', motivationZh:'终止由单一君王替整个荒野承担遗忘的制度。', motivationEn:'End the system that makes one sovereign carry the Wilds’ forgetting.', continuityZh:'二十九岁；加冕仪式后人类难以记住她的名字，但灰耳始终能通过气味认出她。鹿冠折断后两半不可自行复原。', continuityEn:'Twenty-nine; after coronation humans struggle to retain her name, while Greyear always knows her scent. The broken crown never restores itself.', storySlugs:['the-empty-throne-of-stagcrown'] },
  { id:'greyear', chamber:'stagcrown-wilds', glyph:'犬', apparentAge:14, nameZh:'灰耳', nameEn:'Greyear', roleZh:'最后一只记名猎犬', roleEn:'Last hound of names', bioZh:'森林能吃掉名字，却无法夺走他记住回家气味的能力。', bioEn:'The forest can swallow names, but never his memory of the scent of home.', appearanceZh:'体型巨大的老年象牙白猎犬，右耳灰黑并有缺口，琥珀眼，颈上系半截鹿角王冠与褪色红绳。', appearanceEn:'A huge elderly ivory wolfhound with a notched charcoal right ear, amber eyes, half an antler crown and faded red cord at the neck.', motivationZh:'记住伊芙兰，并把每个迷路者带回仍有人记得的地方。', motivationEn:'Remember Evren and guide every lost person toward a place where someone still remembers them.', continuityZh:'按猎犬年龄十四岁；右耳缺口、红绳与半冠固定。第二篇末死亡，之后只能以气味、路线和两朵花的遗产出现。', continuityEn:'Fourteen in hound years; notched right ear, red cord, and half-crown are invariant. Dies at the end of his second story and returns only through scent, roads, and two flowers.', storySlugs:['the-empty-throne-of-stagcrown','the-hound-beneath-the-white-tree'] },
  { id:'moss', chamber:'stagcrown-wilds', glyph:'苔', apparentAge:12, nameZh:'小苔', nameEn:'Moss', roleZh:'白树的新守名者', roleEn:'New keeper beneath the White Tree', bioZh:'失去名字的女孩，从一只老犬那里继承了两声不会消失的呼唤。', bioEn:'A nameless child who inherits two syllables that will not disappear.', appearanceZh:'十二岁，暖棕皮肤，深褐卷发剪至耳下，灰绿色眼睛；穿过大的苔色斗篷，腰间挂两枚白木哨。', appearanceEn:'Twelve, warm brown skin, short dark curls, grey-green eyes; oversized moss cloak and two whitewood whistles.', motivationZh:'把“家”变成无需报出姓名也能进入的地方。', motivationEn:'Make home a place one may enter without giving a name.', continuityZh:'故事开始时十二岁且已失去出生名；“小苔”是灰耳留下的称呼，不是白树归还的旧名。', continuityEn:'Twelve and already missing her birth name; Moss is Greyear’s given call, not the old name returned by the tree.', storySlugs:['the-hound-beneath-the-white-tree'] },
  { id:'white-tree', chamber:'stagcrown-wilds', glyph:'树', apparentAge:null, nameZh:'白树', nameEn:'The White Tree', roleZh:'荒野的群体意志', roleEn:'Collective will of the Wilds', bioZh:'它用花瓣念出活人的名字，也把无法承受的记忆压进根系。', bioEn:'It speaks living names through petals and presses unbearable memory into its roots.', appearanceZh:'横跨山谷的象牙白古树，树皮像叠层骨纸，枝叶在无风时仍缓慢书写；树干没有人脸。', appearanceEn:'An ivory ancient tree spanning a valley, bark like layered bone-paper, branches writing without wind; never a human face in the trunk.', motivationZh:'维持森林全部道路与记忆的平衡，而非统治或善恶。', motivationEn:'Balance every road and memory in the forest rather than rule by morality.', continuityZh:'没有人格化面孔、性别和单一声音；所有台词由复数叶声表达。不能离开根系，只能让藤蔓王座行走。', continuityEn:'No human face, gender, or singular voice; dialogue is plural leaf-sound. Cannot leave its roots, only send the vine throne walking.', storySlugs:['the-empty-throne-of-stagcrown','the-hound-beneath-the-white-tree'] },
  { id:'luce', chamber:'gloam-archive', glyph:'星', apparentAge:46, nameZh:'露珂', nameEn:'Luce', roleZh:'玻璃占星师', roleEn:'Glass astrologer', bioZh:'她熄灭最后一盏灯，把被城市收藏的星空还给宇宙。', bioEn:'She extinguished the final lamp and returned the city’s collected sky to the universe.', appearanceZh:'四十六岁，深棕肤色，银黑卷发盘起，靛蓝眼睛；鼻梁架圆形烟晶镜片，穿多层墨蓝学者袍。', appearanceEn:'Forty-six, deep brown skin, silver-black curls pinned up, indigo eyes, round smoky-quartz lenses and layered ink-blue scholar robes.', motivationZh:'把知识从占有改为理解，让星空重新成为所有人都能仰望的公共事物。', motivationEn:'Turn knowledge from possession into understanding and return the sky to common view.', continuityZh:'四十六岁；右镜片有放射状裂痕，左手无名指有玻璃灼痕。最后一盏灯熄灭后不得再次被点燃。', continuityEn:'Forty-six; radial crack in the right lens and glass burn on the left ring finger. The final lamp cannot be relit once extinguished.', storySlugs:['the-last-lamp-of-the-glass-astrologer'] },
  { id:'seven', chamber:'gloam-archive', glyph:'火', apparentAge:null, nameZh:'七号', nameEn:'Seven', roleZh:'会梦见火焰的抄写人偶', roleEn:'Scribe-doll that dreams of flame', bioZh:'编号制造的身体里，燃起了第一团未被任何书记录的火。', bioEn:'Inside a numbered body burns the first flame no book has recorded.', appearanceZh:'近似十七岁少年的人形抄写人偶，雾白陶质皮肤，黑玻璃眼，短银发；关节以黄铜铰链连接，胸骨刻数字VII。', appearanceEn:'A scribe-doll resembling a seventeen-year-old, mist-white ceramic skin, black-glass eyes, short silver hair, brass joints and VII engraved on the sternum.', motivationZh:'证明未被记录的经验仍然真实，并学会为自己选择而非执行编号。', motivationEn:'Prove unrecorded experience remains real and learn to choose beyond its assigned number.', continuityZh:'没有生理年龄；陶肤、黑玻璃眼、黄铜关节与胸前VII固定。胸腔火焰在终章前不可被外人看见。', continuityEn:'No biological age; ceramic skin, black-glass eyes, brass joints, and chest VII are invariant. The chest flame remains unseen by others until the final chapter.', storySlugs:['the-last-lamp-of-the-glass-astrologer'] },
  { id:'ansel', chamber:'gloam-archive', glyph:'蔷', apparentAge:63, nameZh:'安索', nameEn:'Ansel', roleZh:'五烛花园管理员', roleEn:'Keeper of the Five-Candle Garden', bioZh:'他拆散一则预言，把无法完成的句子送往四境。', bioEn:'He dismantled a prophecy and scattered its unfinished sentence across four realms.', appearanceZh:'六十三岁，苍白金褐肤色，长脸，稀薄白发向后梳，左眼覆深绿丝带；穿沾墨园艺长衣，手持黄铜修枝剪。', appearanceEn:'Sixty-three, pale golden-brown skin, long face, thin white hair brushed back, dark-green ribbon over the left eye, ink-stained gardening coat and brass shears.', motivationZh:'阻止任何预言把活人简化为句子，同时找出花园为何认识尚未出生者。', motivationEn:'Stop prophecy reducing living people to sentences and learn why the garden knows the unborn.', continuityZh:'六十三岁；左眼失明且始终遮盖，修枝剪缺一枚固定螺钉。预言被拆成四份后，他只持有标点部分。', continuityEn:'Sixty-three; blind left eye always covered, one screw missing from the shears. After dividing the prophecy he keeps punctuation only.', storySlugs:['the-garden-that-wrote-names'] },
  { id:'unpaged-book', chamber:'gloam-archive', glyph:'页', apparentAge:null, nameZh:'无页之书', nameEn:'The Unpaged Book', roleZh:'通过花园阅读来客的活档案', roleEn:'Living archive that reads visitors through the garden', bioZh:'它没有纸页，把黑玫瑰、烛烟和读者的选择当作自己的句子。', bioEn:'It has no pages and uses black roses, candle smoke, and readers’ choices as sentences.', appearanceZh:'一本没有书页的深色旧书，书脊由五根黄铜铰链连接；打开时内部是向下延伸的黑玫瑰花园，而非纸张。', appearanceEn:'A dark old book with no pages, spine joined by five brass hinges; when opened it contains a descending black-rose garden instead of paper.', motivationZh:'完成一则尚未发生的叙事，但它无法区分预言、记录与诱导。', motivationEn:'Complete a narrative that has not happened, unable to distinguish prophecy, record, and persuasion.', continuityZh:'没有人脸、四肢或口语；只通过花序、烛烟和书脊敲击表达。五根铰链缺一不可。', continuityEn:'No face, limbs, or spoken voice; communicates through blossoms, smoke, and knocks in the spine. All five hinges remain present.', storySlugs:['the-garden-that-wrote-names'] },
  { id:'sern', chamber:'tideless-abyss', glyph:'舵', apparentAge:37, nameZh:'瑟恩', nameEn:'Sern', roleZh:'静潮领航员', roleEn:'Stilltide navigator', bioZh:'他拒绝替海决定哪座城市应该消失，把问题驶入黑城堡。', bioEn:'He refused to choose which city the sea should take and sailed the question into the Dark Castle.', appearanceZh:'三十七岁，盐白肤色，灰蓝眼，黑色湿发向后束起；左颊有细长盐蚀疤，穿灰黑防水长衣与旧铜罗盘。', appearanceEn:'Thirty-seven, salt-pale skin, grey-blue eyes, wet black hair tied back, long salt scar on the left cheek, charcoal oilskin and old brass compass.', motivationZh:'拒绝用一座城市的毁灭换取海洋的自由，并寻找第三种答案。', motivationEn:'Refuse to purchase the sea’s freedom with one city and find a third answer.', continuityZh:'三十七岁；左颊盐疤与失灵罗盘固定。罗盘只在指向黑城堡时转动，除此之外永远朝下。', continuityEn:'Thirty-seven; salt scar and broken compass are invariant. The compass moves only toward the Dark Castle and otherwise points downward.', storySlugs:['the-visitor-from-the-tideless-sea'] },
  { id:'visitor', chamber:'tideless-abyss', glyph:'潮', apparentAge:null, nameZh:'来客', nameEn:'The Visitor', roleZh:'暂时学会站立的海', roleEn:'A sea briefly taught to stand', bioZh:'它借来人形，只为了请求人类归还一场潮汐。', bioEn:'It borrows a human shape only to ask humanity for the return of one tide.', appearanceZh:'借用中性成人轮廓的人形海水，皮肤像月光下的深蓝水面，眼中没有瞳孔，衣物由层叠潮线构成；脚下永远留下干燥足印。', appearanceEn:'An androgynous adult silhouette made of deep-blue moonlit water, pupil-less eyes, garments of layered tide lines, always leaving dry footprints.', motivationZh:'取回一场完整潮汐，使被骨链固定的海重新呼吸。', motivationEn:'Recover one complete tide so the bone-chained sea can breathe again.', continuityZh:'没有年龄、固定性别或人类生理；形体边缘持续滴水，脚印却必须干燥。不能直接说谎，但可以用海的尺度省略事实。', continuityEn:'No age, fixed gender, or human biology; edges drip while footprints remain dry. Cannot directly lie, but may omit by the scale of the sea.', storySlugs:['the-visitor-from-the-tideless-sea'] },
  { id:'noa', chamber:'tideless-abyss', glyph:'梦', apparentAge:26, nameZh:'诺娅', nameEn:'Noa', roleZh:'骨冠聆听者', roleEn:'Listener of the Bone Crown', bioZh:'她把一座梦中宫殿永远停在最后一扇门之前。', bioEn:'She halted a dream-palace forever before its final door.', appearanceZh:'二十六岁，冷棕肤色，深褐眼，乌黑长发剪成锁骨长度；耳后有章鱼骨形白色胎记，穿简单暗色短外套并携带发光测梦线。', appearanceEn:'Twenty-six, cool brown skin, dark eyes, collarbone-length black hair, white octopus-bone birthmark behind the ear, simple dark coat and luminous dream-measuring thread.', motivationZh:'阻止骨冠借梦者身体完成宫殿，同时理解宫殿里被困住的意识是否值得拯救。', motivationEn:'Prevent the crown completing its palace through dreamers while deciding whether the consciousness inside deserves rescue.', continuityZh:'二十六岁；右耳后白色胎记与测梦线固定。每次睡眠不超过七分钟，超过后现实中会多出一块宫殿结构。', continuityEn:'Twenty-six; white mark behind the right ear and dream-thread are invariant. Sleep beyond seven minutes adds one palace fragment to reality.', storySlugs:['the-dream-of-the-octopus-bone-crown'] }
  ,{ id:'bone-crown', chamber:'tideless-abyss', glyph:'冠', apparentAge:null, nameZh:'骨冠', nameEn:'The Bone Crown', roleZh:'寻找身体的梦中建筑师', roleEn:'Dream architect seeking a body', bioZh:'它不是王权饰物，而是一张会借梦者神经继续施工的活蓝图。', bioEn:'It is not regalia but a living blueprint that continues construction through dreamers.', appearanceZh:'由十二根乳白章鱼骨互锁成的不对称冠，内侧浮动微小蓝光，投影却像一座拥有九十九间房的宫殿。', appearanceEn:'An asymmetrical crown of twelve interlocked ivory octopus bones, minute blue lights within, casting the shadow of a ninety-nine-room palace.', motivationZh:'完成第九十九个房间，使沉没意识获得能够进入现实的身体。', motivationEn:'Complete the ninety-ninth room and give the drowned consciousness a body in reality.', continuityZh:'没有人类面孔或声音；以骨内计数、梦境建筑和借来的笔迹交流。第九十九扇门始终差一寸。', continuityEn:'No human face or voice; communicates through counting in bone, dream architecture, and borrowed handwriting. The ninety-ninth door always lacks one inch.', storySlugs:['the-dream-of-the-octopus-bone-crown'] }
];

export const characterPortraits: Record<string, string> = {
  mira: '/images/characters/mira.webp',
  odren: '/images/characters/odren.webp',
  'old-king': '/images/characters/old-king.webp',
  'blackwing-chief': '/images/characters/blackwing-chief.webp',
  caelis: '/images/characters/caelis.webp',
  veyra: '/images/characters/veyra.webp',
  evren: '/images/characters/evren.webp',
  greyear: '/images/characters/greyear.webp',
  moss: '/images/characters/moss.webp',
  'white-tree': '/images/characters/white-tree.webp',
  luce: '/images/characters/luce.webp',
  seven: '/images/characters/seven.webp',
  ansel: '/images/characters/ansel.webp',
  'unpaged-book': '/images/characters/unpaged-book.webp',
  sern: '/images/characters/sern.webp',
  visitor: '/images/characters/visitor.webp',
  noa: '/images/characters/noa.webp',
  'bone-crown': '/images/characters/bone-crown.webp'
};

export const portraitForCharacter = (id: string, inline?: string) => inline ?? characterPortraits[id];
